version: "3.8"

services:
  dev_api:
    container_name: dev_api
    build:
      context: .
    working_dir: /home/node/app
    user: node
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 3333:3333
      - 9229:9229
    networks:
      - app-network
    volumes:
      - .:/home/node/app

  dev_postgres:
    container_name: dev_postgres
    image: postgres:13
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: